package resources

import (
	"crypto/sha256"
	"fmt"

	"gopkg.in/yaml.v3"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	gatewayv1alpha1 "github.com/jkaninda/goma-operator/api/v1alpha1"
	"github.com/jkaninda/goma-operator/internal/config"
)

const (
	ConfigFileName = "goma.yml"
)

// BuildConfigMap creates a ConfigMap containing the generated goma.yml.
func BuildConfigMap(gw *gatewayv1alpha1.Gateway, cfg config.GatewayConfig) (*corev1.ConfigMap, string, error) {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, "", fmt.Errorf("failed to marshal gateway config: %w", err)
	}

	header := fmt.Sprintf("# Goma Gateway configuration for %q\n# Generated by goma-operator — DO NOT EDIT MANUALLY\n\n", gw.Name)
	configData := header + string(data)

	checksum := fmt.Sprintf("%x", sha256.Sum256([]byte(configData)))

	cm := &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      ConfigMapName(gw.Name),
			Namespace: gw.Namespace,
			Labels:    CommonLabels(gw.Name),
		},
		Data: map[string]string{
			ConfigFileName: configData,
		},
	}

	return cm, checksum, nil
}

// ConfigMapName returns the ConfigMap name for a gateway.
func ConfigMapName(gatewayName string) string {
	return gatewayName + "-goma-config"
}
